import { Product } from './product';

export var list_product: Product[] = [
    { id: 1, name: 'white T-Shirt', img: 'images/p1.jpg', price: 300, price_sale: 280,
        brief: 'Wattle seed bunya nuts spring onion okra garlic bitterleaf zucchini', product_cate_id: 1,
        detail: "Look knock-out on nights out in figure-skimming bodycon fits, flowing maxi lengths and stunning sequin-embellished occasion dresses. This season make for satin sheen slip dresses in mink nudes, and match lace trim cami dresses with barely-there heels for that cocktail-ready combo. If glitterball gowns aren't your thing, take to the dance floor in a tux dress for an all-eyes-on-you androgynous look.",
        inventory: 1, partner_id: 1, state: 'inactive', views: 100, created: 1476910059004, updated: 1476910059004, status: 1,
    },
    { id: 2, name: 'yellow T-Shirt', img: 'images/p2.jpg', price: 280, price_sale: 0,
        brief: 'Wattle seed bunya nuts spring onion okra garlic bitterleaf zucchini', product_cate_id: 1,
        detail: "Look knock-out on nights out in figure-skimming bodycon fits, flowing maxi lengths and stunning sequin-embellished occasion dresses. This season make for satin sheen slip dresses in mink nudes, and match lace trim cami dresses with barely-there heels for that cocktail-ready combo. If glitterball gowns aren't your thing, take to the dance floor in a tux dress for an all-eyes-on-you androgynous look.",
         inventory: 1, partner_id: 1, state: 'inactive', views: 100, created: 1475539959004, updated: 1475539959004, status: 1,
    },
    { id: 3, name: 'black skirt', img: 'images/p3.jpg', price: 350, price_sale: 300,
        brief: 'Wattle seed bunya nuts spring onion okra garlic bitterleaf zucchini', product_cate_id: 2,
        detail: "Look knock-out on nights out in figure-skimming bodycon fits, flowing maxi lengths and stunning sequin-embellished occasion dresses. This season make for satin sheen slip dresses in mink nudes, and match lace trim cami dresses with barely-there heels for that cocktail-ready combo. If glitterball gowns aren't your thing, take to the dance floor in a tux dress for an all-eyes-on-you androgynous look.",
         inventory: 1, partner_id: 1, state: 'inactive', views: 100, created: 1474425059004, updated: 1474425059004, status: 1,
    },
    { id: 4, name: 'red dress', img: 'images/p4.jpg', price: 190, price_sale: 0,
        brief: 'Wattle seed bunya nuts spring onion okra garlic bitterleaf zucchini', product_cate_id: 3,
        detail: "Look knock-out on nights out in figure-skimming bodycon fits, flowing maxi lengths and stunning sequin-embellished occasion dresses. This season make for satin sheen slip dresses in mink nudes, and match lace trim cami dresses with barely-there heels for that cocktail-ready combo. If glitterball gowns aren't your thing, take to the dance floor in a tux dress for an all-eyes-on-you androgynous look.",
         inventory: 1, partner_id: 1, state: 'inactive', views: 100, created: 1472925059004, updated: 1472925059004, status: 1,
    },
    { id: 5, name: 'gray dress', img: 'images/p5.jpg', price: 258, price_sale: 230,
        brief: 'Wattle seed bunya nuts spring onion okra garlic bitterleaf zucchini', product_cate_id: 3,
        detail: "Look knock-out on nights out in figure-skimming bodycon fits, flowing maxi lengths and stunning sequin-embellished occasion dresses. This season make for satin sheen slip dresses in mink nudes, and match lace trim cami dresses with barely-there heels for that cocktail-ready combo. If glitterball gowns aren't your thing, take to the dance floor in a tux dress for an all-eyes-on-you androgynous look.",
         inventory: 1, partner_id: 1, state: 'inactive', views: 100, created: 1473899959004, updated: 1473899959004, status: 1,
    },
    { id: 6, name: 'blue Shirt', img: 'images/p6.jpg', price: 410, price_sale: 390,
        brief: 'Wattle seed bunya nuts spring onion okra garlic bitterleaf zucchini', product_cate_id: 1,
        detail: "Look knock-out on nights out in figure-skimming bodycon fits, flowing maxi lengths and stunning sequin-embellished occasion dresses. This season make for satin sheen slip dresses in mink nudes, and match lace trim cami dresses with barely-there heels for that cocktail-ready combo. If glitterball gowns aren't your thing, take to the dance floor in a tux dress for an all-eyes-on-you androgynous look.",
         inventory: 1, partner_id: 1, state: 'inactive', views: 100, created: 1471966959004, updated: 1471966959004, status: 1,
    },
    { id: 7, name: 'black dress', img: 'images/p7.jpg', price: 321, price_sale: 0,
        brief: 'Wattle seed bunya nuts spring onion okra garlic bitterleaf zucchini', product_cate_id: 3,
        detail: "Look knock-out on nights out in figure-skimming bodycon fits, flowing maxi lengths and stunning sequin-embellished occasion dresses. This season make for satin sheen slip dresses in mink nudes, and match lace trim cami dresses with barely-there heels for that cocktail-ready combo. If glitterball gowns aren't your thing, take to the dance floor in a tux dress for an all-eyes-on-you androgynous look.",
         inventory: 1, partner_id: 1, state: 'inactive', views: 100, created: 1476689959004, updated: 1476689959004, status: 1,
    },
    { id: 8, name: 'white dress', img: 'images/p8.jpg', price: 256, price_sale: 210,
        brief: 'Wattle seed bunya nuts spring onion okra garlic bitterleaf zucchini', product_cate_id: 3,
        detail: "Look knock-out on nights out in figure-skimming bodycon fits, flowing maxi lengths and stunning sequin-embellished occasion dresses. This season make for satin sheen slip dresses in mink nudes, and match lace trim cami dresses with barely-there heels for that cocktail-ready combo. If glitterball gowns aren't your thing, take to the dance floor in a tux dress for an all-eyes-on-you androgynous look.",
         inventory: 1, partner_id: 1, state: 'inactive', views: 100, created: 1472359959004, updated: 1472359959004, status: 1,
    },
    { id: 9, name: 'purple dress', img: 'images/p9.jpg', price: 648, price_sale: 550,
        brief: 'Wattle seed bunya nuts spring onion okra garlic bitterleaf zucchini', product_cate_id: 3,
        detail: "Look knock-out on nights out in figure-skimming bodycon fits, flowing maxi lengths and stunning sequin-embellished occasion dresses. This season make for satin sheen slip dresses in mink nudes, and match lace trim cami dresses with barely-there heels for that cocktail-ready combo. If glitterball gowns aren't your thing, take to the dance floor in a tux dress for an all-eyes-on-you androgynous look.",
         inventory: 1, partner_id: 1, state: 'inactive', views: 100, created: 14750757959004, updated: 14750757959004, status: 1,
    },
]